# Generated by Django 4.2.13 on 2026-07-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country_code',
            field=models.CharField(default='+91', help_text='Country code e.g. +91, +1', max_length=5),
        ),
    ]
